@extends('admin.layouts.app')
@section('title', 'Categories')
@section('content')
<div class="mb-4"><div class="eyebrow mb-2">Content</div><h1 class="h3 mb-1">Job categories</h1><p class="text-muted mb-0">Keep the qualification navigation organized.</p></div>
<div class="row g-4"><div class="col-xl-8"><div class="panel"><div class="panel-header"><h2 class="h5 mb-0">All categories</h2></div><div class="table-responsive"><table class="table"><thead><tr><th>Name</th><th>Slug</th><th>Jobs</th><th>Status</th><th></th></tr></thead><tbody>@forelse($categories as $category)<tr><td><form method="POST" action="{{ route('admin.categories.update', $category) }}" class="d-flex gap-2">@csrf @method('PUT')<input class="form-control form-control-sm" name="name" value="{{ $category->name }}"><input type="hidden" name="slug" value="{{ $category->slug }}"><input type="hidden" name="sort_order" value="{{ $category->sort_order }}"><input type="hidden" name="is_active" value="{{ $category->is_active ? 1 : 0 }}"></td><td class="text-muted">{{ $category->slug }}</td><td>{{ $category->jobs_count }}</td><td><button class="btn btn-sm btn-link text-decoration-none p-0">{{ $category->is_active ? 'Active' : 'Inactive' }}</button></td><td class="text-end"><button class="btn btn-sm btn-outline-primary"><i class="bi bi-check2"></i></button></form><form method="POST" action="{{ route('admin.categories.destroy', $category) }}" class="d-inline" onsubmit="return confirm('Delete this category?')">@csrf @method('DELETE')<button class="btn btn-sm btn-outline-danger"><i class="bi bi-trash"></i></button></form></td></tr>@empty<tr><td colspan="5" class="text-center text-muted py-5">No categories yet.</td></tr>@endforelse</tbody></table></div></div></div><div class="col-xl-4"><div class="panel"><div class="panel-header"><h2 class="h5 mb-0">Add category</h2></div><div class="panel-body"><form method="POST" action="{{ route('admin.categories.store') }}">@csrf<div class="mb-3"><label class="form-label">Name</label><input class="form-control" name="name" required placeholder="10th Pass"></div><div class="mb-3"><label class="form-label">Slug <span class="text-muted">optional</span></label><input class="form-control" name="slug"></div><div class="mb-3"><label class="form-label">Display order</label><input class="form-control" name="sort_order" type="number" value="10" required></div><input type="hidden" name="is_active" value="1"><button class="btn btn-primary w-100">Add category</button></form></div></div></div></div>
@if($categories->hasPages())
	<div class="mt-3"><x-pagination :paginator="$categories" /></div>
@endif
@endsection
